# Generated by Django 6.0.6 on 2026-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('course', models.CharField(choices=[('spring', 'spring boot'), ('python stack', 'python stack'), ('mern stack', 'mern stack')], max_length=20)),
            ],
        ),
    ]
