# Generated by Django 6.0.6 on 2026-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('python stack', 'python stack'), ('mern stack', 'mern stack'), ('spring', 'spring boot')], max_length=20),
        ),
    ]
