# Generated by Django 6.0.6 on 2026-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('Mern stack', 'Mern stack'), ('Python stack', 'Python stack'), ('Spring boot', 'Spring boot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
